baseURL: 'https://synthcard.com/'
languageCode: en-us
title: The SynthCard Project
paginate: 1000
theme: showcase

params:
  author: "Benjie Jiao"
  description: "The official website for the SynthCard project"
  message: "A collection of business-card sized synthesizer modules made by members of the SynthDIY community."
